import rsa
import stdio
import sys


# Entry point.
def main():
   #Accept n and d as command line arguments
    n = int(sys.argv[1])
    d = int(sys.argv[2])

    #Get the number of bits per character (call it width)
    Width = rsa.bitLength(n)

    #Accept message (binary string generated by encrypt.py) from standard input.
    Message = stdio.readAll()

    #heheh cute

    #for i in range (0, length message -1, incremeant by width)
    for i in range(0, len(Message) - 1, Width):
        
        #set s to sub string; i --> i + width (slice into string using index = ending exclsuive*)
        s = Message[i: i + Width]
        
        # y = dec. rep. of binary string of s
        y = rsa.bin2dec(s)
        
        #decrypt y 
        decy = rsa.decrypt(y, n, d)
        
        #write decrypted value using chr()
        stdio.write(chr(decy))


if __name__ == '__main__':
    main()
